export const projects = [
    {
        id: 1,
        title: 'Stitch : E-Commerce Platform',
        category: 'fullstack',
        image: 'https://res.cloudinary.com/dya8ig3jg/image/upload/v1749280864/stitch_zzrn78.png',
        tech: ['SpringBoot', 'React', 'Redux', 'PostgreSQL', 'Razorpay'],
        description: 'A full-stack e-commerce platform with user authentication, product & order management, Razorpay payment integration, and a responsive UI for seamless shopping experiences.',
        githubLink: 'https://github.com/nil-official/Stitch/',
    },
    {
        id: 2,
        title: 'Cinemax : Movie Ticket Booking',
        category: 'fullstack',
        image: 'https://res.cloudinary.com/dya8ig3jg/image/upload/v1749280867/cinemax_iw5dac.png',
        tech: ['Express', 'React', 'Material UI', 'MongoDB', 'Razorpay'],
        description: 'A feature-rich online movie ticket booking system built using the MERN stack, designed to provide a seamless booking experience for users.',
        githubLink: 'https://github.com/nil-official/Cinemax/',
    },
    {
        id: 3,
        title: 'QuizWhiz : Quiz Application',
        category: 'frontend',
        image: 'https://res.cloudinary.com/dya8ig3jg/image/upload/v1749280861/quizwhiz_vtpucy.png',
        tech: ['Next', 'Redux'],
        description: 'An interactive quiz application for self-assessment. It offers a user-friendly interface, real-time feedback, and a variety of quiz categories to enhance learning and knowledge retention.',
        githubLink: 'https://github.com/nil-official/QuizWhiz/',
        demoLink: 'https://quiz-whiz-livid.vercel.app/',
    },
    {
        id: 4,
        title: 'Learnify : Landing Page',
        category: 'frontend',
        image: 'https://res.cloudinary.com/dya8ig3jg/image/upload/v1749280865/learnify_vajz1y.png',
        tech: ['React', 'Tailwind CSS'],
        description: 'A responsive landing page for an online learning platform, showcasing courses, testimonials, and a user-friendly interface.',
        githubLink: 'https://github.com/nil-official/Learnify/',
        demoLink: 'https://nil-official.github.io/Learnify/',
    },
    {
        id: 5,
        title: 'To Do List',
        category: 'frontend',
        image: 'https://res.cloudinary.com/dya8ig3jg/image/upload/v1749280864/todo_lexf0b.png',
        tech: ['React', 'Tailwind CSS'],
        description: 'A simple and intuitive to-do list application that allows users to manage tasks efficiently. It features task creation, editing, and deletion functionalities.',
        githubLink: 'https://github.com/nil-official/To-Do-List/',
        demoLink: 'https://nil-official.github.io/To-Do-List/',
    },
    {
        id: 6,
        title: 'Palette : OTT Platform',
        category: 'fullstack',
        tech: ['JSP', 'Servlet', 'OracleDB', 'HTML', 'CSS'],
        description: 'An OTT platform enabling user authentication, video streaming, and content management with a dynamic front-end and database integration.',
        githubLink: 'https://github.com/nil-official/Palette/',
    },
    {
        id: 7,
        title: 'Tic Tac Toe',
        category: 'game',
        image: 'https://res.cloudinary.com/dya8ig3jg/image/upload/v1749280864/tictactoe_mxer94.png',
        tech: ['React', 'Tailwind CSS'],
        description: 'A classic Tic Tac Toe game built with React, featuring a user-friendly interface and real-time gameplay.',
        githubLink: 'https://github.com/nil-official/Tic-Tac-Toe/',
        demoLink: 'https://nil-official.github.io/Tic-Tac-Toe/',
    }
]